sim:
    isRunNow: true
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 3
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0
    priority: true
    vin_start: 100000

node:
    id: 1001
    name: node-up

mq:
    log:
        url: tcp://log.activemq.soaringlab.top:61616
    send:
        url: tcp://up.activemq.soaringlab.top:60001
    receive:
        SOUTH:
            distance: 40
            channel: NORTH
            url: tcp://center.activemq.soaringlab.top:60000


#               up:60001
#left:60004     center:60000    right:60002
#               down:60003