sim:
    isRunNow: true
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 3
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0
    priority: false
    vin_start: 1

node:
    id: 1000
    name: node-center


mq:
    log:
        url: tcp://log.activemq.soaringlab.top:61616
    send:
        url: tcp://center.activemq.soaringlab.top:60000
    receive:
        WEST:
            distance: 40
            channel: EAST
            url: tcp://left.activemq.soaringlab.top:60004
        

#left:60004     center:60000
#               down:60003
