sim:
    isRunNow: true
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 3
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0
    priority: true
    vin_start: 400000

node:
    id: 1004
    name: node-left

mq:
    log:
        url: tcp://log.soaringlab.top:61616
    send:
        url: tcp://left.soaringlab.top:60004
    receive:
        WEST:
            distance: 400
            channel: EAST
            url: tcp://center.soaringlab.top:60000


#left:60004     center:60000    right:60002
#               down:60003