sim:
    isRunNow: true
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 3
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0
    priority: true
    vin_start: 1
    
node:
    id: 1000
    name: node-center


mq:
    log:
        url: tcp://log.activemq.soaringlab.top:61616
    send:
        url: tcp://center.activemq.soaringlab.top:60000
    receive:
        NORTH:
            distance: 40
            channel: SOUTH
            url: tcp://up.activemq.soaringlab.top:60001
        EAST:
            distance: 40
            channel: WEST
            url: tcp://right.activemq.soaringlab.top:60002
        SOUTH:
            distance: 40
            channel: NORTH
            url: tcp://down.activemq.soaringlab.top:60003
        WEST:
            distance: 40
            channel: EAST
            url: tcp://left.activemq.soaringlab.top:60004

#               up:60001
#left:60004     center:60000    right:60002
#               down:60003
