sim:
    isRunNow: false
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 3
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0

mq:
    send:
        url: tcp://localhost:61616
    receive:
        SOUTH:
            destination: SOUTH
            url: tcp://localhost:61616
        EAST:
            destination: EAST
            url: tcp://localhost:61616
        NORTH:
            destination: NORTH
            url: tcp://localhost:61616
        WEST:
            destination: WEST
            url: tcp://localhost:61616
