sim:
    isRunNow: false
    columns: 1
    rows: 1
    lane_width: 4
    speed_limit: 25.0
    lanes_per_road: 1
    median_size: 1
    distance_between: 150
    traffic_level: 0.28
    stop_distance_before_intersection: 1.0
    vin_start: 10000
    
mq:
    send:
        url: tcp://center.soaringlab.top:61616
    receive:
        NORTH:
            channel: SOUTH
            url: tcp://up.soaringlab.top:61616
        EAST:
            channel: WEST
            url: tcp://right.soaringlab.top:61616
        SOUTH:
            channel: NORTH
            url: tcp://down.soaringlab.top:61616
#        WEST:
#            channel: EAST
#            url: tcp://left.soaringlab.top:61616
